apiVersion: v1
kind: Service
metadata:
  name: vibegram-backend-service
  namespace: vibegram
  labels:
    app: vibegram-backend
spec:
  type: ClusterIP
  selector:
    app: vibegram-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
